import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["400", "600"], 
  variable: "--font-poppins"  // custom css variable
});

export const metadata = {
  title: "CodeSnytax",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
  {children}
      </body>
    </html>
  );
}
